### PR TITLE
set launchpad noida to seat full

### PR DESCRIPTION
**Pull request by KeenWarrior**

### CODE REVIEW

**Comment by KeenWarrior** [comment]
@championswimmer @witty123 urgent

**Comment by witty123** [comment]
@KeenWarrior not able to see reflected changes in deployment preview of c+ for beginners page. Can you check what's wrong ?

**Comment by KeenWarrior** [comment]
screen shot 2018-05-19 at 5 56 21 pm

**Comment by KeenWarrior** [comment]
screen shot 2018-05-25 at 3 34 53 pm

**Pull request merged**
