### PR TITLE
fixed python course content css

### PR DESCRIPTION
**Pull request by hereisnaman**
fixes: https://github.com/coding-blocks/codingblocks.com/issues/325

### CODE REVIEW

**Comment by championswimmer** [comment]
are you kidding me  ? 
remove "bg-dark" class from html simply :| 
why edit custom CSS

**Comment by hereisnaman** [comment]
Did not know if wanted to remove the dark section or to fix css.

**Comment by championswimmer** [comment]
Your fix breaks all other pages :P

**Comment by abhishek97** [comment]
screen shot 2017-12-28 at 11 08 58 pm
@hereisnaman Breaking all pages at once is quite an achievement in itself. 😸

**Pull request closed without merging**
