### PR TITLE
added error message if no events are available

### LINKED ISSUE #443: [improvement suggestion] add a message if no events are there
noeventspresent

If no past/upcoming events are there, then atleast provide a suitable message so  that the page does not look this passive...

This suggestion is in reference to the issue #29 .

### PR DESCRIPTION
**Pull request by nikhilmufc7**
fixes #443

### CODE REVIEW

**Comment by nikhilmufc7** [comment]
[](url)

**Comment by nikhilmufc7** [comment]
screen shot 2018-05-21 at 5 15 18 pm

**Comment by nikhilmufc7** [comment]
screen shot 2018-05-21 at 5 15 18 pm
screen shot 2018-05-21 at 5 15 39 pm

**Comment by witty123** [comment]
This is no longer required.

**Pull request closed without merging**
