### PR TITLE
Added Navbar on scroll

### LINKED ISSUE #513: Navbar on Scroll
Its my suggestion as all the pages are too scrollable and if a person wants from middle to change the page for that he wants to go to again the top of the page to choose from navbar
Instead of Navbar only shows on top, if a user backscroll from any instance the navbar should appear.
i.e the navbar will be visible again if someone scroll Up.
with reference to #29

### PR DESCRIPTION
**Pull request by architkshk**
Fixes #513

### CODE REVIEW

**Comment by witty123** [comment]
When I scroll up after scrolling down, the page abruptly goes to the top. Instead we want to make the navbar sticky.

**Comment by architkshk** [comment]
ezgif com-optimize
@witty123 works fine for me.

**Comment by witty123** [comment]
@architkshk any updates ?

**Comment by architkshk** [comment]
will do it today.

**Comment by architkshk** [comment]
@witty123 Done!

**Comment by architkshk** [comment]
@witty123 review this too

**Comment by witty123** [comment]
@architkshk not able to scroll expanded navbar

**Pull request merged**
